name: "Run Terraform plan"

on:
  workflow_dispatch:

jobs:
  call-terraform-plan:
    uses: fapd777/terraform-workflow/.github/workflows/terraform-plan.yml@main
    secrets:
      aws_sts_credentials_json: ${{ secrets.AWS_STS_CREDENTIALS_JSON }}
